### ISSUE TITLE
Galaxy-10 missing images

### ISSUE THREAD

**Issue by neel-dey** [henrysky/astroNN#11]
I was considering doing a few demos with the `Galaxy10` dataset but noticed that the `Galaxy10.h5` file linked [here](https://astronn.readthedocs.io/en/latest/galaxy10.html) has 21785 images and not the 25753 stated on the webpage. Was this a typo or are some images missing?

Thanks for assembling this fun toy dataset :)

**Comment by henrysky** [comment]
I just checked the code that generates `Galaxy10.h5`. I believe the number 25753 comes from an old file which is not published because we eventually increase the threshold in order for a galaxy image to be included, which is `If none of the classes get more than 55%, the image will not be included in Galaxy10 as no agreement was reached`

Thanks for reporting the issue, I have corrected the number on the webpage (bea6f58)
